added fc40, removed fc38

diff --git a/webmail/fc40/Dockerfile b/webmail/fc40/Dockerfile
--- a/webmail/fc40/Dockerfile
+++ b/webmail/fc40/Dockerfile
@@ -1,19 +1,19 @@
-# docker build -f dockerfile.fc38 -t cprogrammer/indimail:fc38
-FROM fedora:38
+# docker build -f dockerfile.fc40 -t cprogrammer/indimail-web:fc40
+FROM fedora:40
 MAINTAINER cprogrammer
-LABEL org.opencontainers.image.source=https://github.com/indimail/indimail:fc38
+LABEL org.opencontainers.image.source=https://github.com/indimail/indimail-web:fc40
 
 RUN export HOSTNAME=indimail.org \
 	MYSQL_SOCKET=/run/mysqld/mysqld.sock \
 	&& sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf \
 	&& dnf -y install 'dnf-command(config-manager)' \
 	&& dnf config-manager \
-		--add-repo https://download.opensuse.org/repositories/home:mbhangui/Fedora_38/home:mbhangui.repo \
-	&& mkdir -p /root \
+		--add-repo https://download.opensuse.org/repositories/home:mbhangui/Fedora_40/home:mbhangui.repo \
+	&& mkdir -p /root/Downloads \
 	&& dnf -y update \
 	&& dnf -y install \
-		gnupg2 \
 		binutils \
+		gnupg2 \
 		hostname \
 		initscripts \
 		less \
@@ -21,9 +21,10 @@ RUN export HOSTNAME=indimail.org \
 		mailx \
 		man-db \
 		man-pages \
+		mrtg \
 		net-tools \
-		openssl \
 		openssh-clients \
+		openssl \
 		procps \
 		psmisc \
 		rsync \
@@ -37,29 +38,38 @@ RUN export HOSTNAME=indimail.org \
 		passwd \
 		iputils \
 		deltarpm \
-		indimail-mta \
-		logalert \
-		procmail \
 		indimail \
-		indimail-auth \
+		indimail-mta \
 		indimail-access \
+		indimail-auth \
 		indimail-utils \
+		indimail-spamfilter \
 		bogofilter-wordlist \
 		ezmlm-idx \
 		ezmlm-idx-cgi \
 		ezmlm-idx-mysql \
+		iwebadmin \
+		httpd \
+		mod_ssl \
+		php \
+		php-fpm \
+		roundcubemail \
+		php-mysqlnd \
+		php-imagick \
+		ircube \
 		perl-Authen-SASL \
 		perl-Digest-HMAC \
 		perl-Digest-SHA \
-	&& dnf -y install \
-		indimail-spamfilter \
 	&& echo "Creating self-signed certificate" \
 	&& /usr/sbin/svctool \
 		--config=cert --postmaster=postmaster@indimail.org \
 		--common_name=indimail.org > /dev/null 2>/tmp/cert.log || \
 		echo "certificate generation failed" \
-	&& /bin/rm -rf /run \
-	&& echo "Build Completed" 
+	&& mkdir -p /var/log/build \
+	&& /usr/libexec/indimail/roundcube_config > /var/log/build/roundcube.log 2>&1 \
+	&& (echo "Build Succeeded" && gzip /var/log/build/roundcube.log) || (echo "Build Failed" && cat /var/log/build/roundcube.log && exit 1) \
+	&& (test -d /var/indimail/mysqldb/data/RoundCube_db && echo "RoundCube db creation succeeded") || \
+		(echo "RoundCube db creation failed" && gunzip -c /var/log/build/roundcube.log.gz && exit 1)
 COPY .alias .bash_profile .bashrc .exrc .gfuncs .glogout .indent.pro .vimrc /root/
 ENTRYPOINT ["docker-entrypoint"]
-CMD ["indimail"]
+CMD ["webmail"]
