added check for roundcube db creation

diff --git a/.github/workflows/buildall-bin-from-obs.yml b/.github/workflows/buildall-bin-from-obs.yml
--- a/.github/workflows/buildall-bin-from-obs.yml
+++ b/.github/workflows/buildall-bin-from-obs.yml
@@ -35,6 +35,7 @@ jobs:
           else
             distros="${{ github.event.inputs.distro_list }}"
           fi
+          flag=""
           for i in $distros
           do
             for j in indimail indimail-mta
@@ -46,11 +47,18 @@ jobs:
                 docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
                 docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
                 docker push docker.io/cprogrammer/$j:$i
+              else
+                cat $i.$j.log
+                flag="$flag $j:$i"
               fi
               /bin/rm -f Dockerfile
               gzip $i.$j.log
             done
           done
+          if [ -n "$flag" ] ; then
+            echo "docker build failed for $flag"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v2
         with:
           name: buildall-bin-from-src
diff --git a/.github/workflows/buildall-bin-from-src.yml b/.github/workflows/buildall-bin-from-src.yml
--- a/.github/workflows/buildall-bin-from-src.yml
+++ b/.github/workflows/buildall-bin-from-src.yml
@@ -6,6 +6,13 @@ name: buildall-bin-from-src push script
 
 on:
   workflow_dispatch:
+    # Inputs the workflow accepts.
+    inputs:
+      distro_list:
+        # Friendly description to be shown in the UI instead of 'name'
+        Distro List: 'distro list'
+        # Input has to be provided for the workflow to run
+        required: false
 
 jobs:
   build_and_push:
@@ -23,7 +30,13 @@ jobs:
       - name: build
         run: |
           set +e
-          for i in alpine archlinux stream8 stream9 ubi8 gentoo
+          if [ -z "${{ github.event.inputs.distro_list }}"  ] ; then
+            distros="alpine archlinux stream8 stream9 ubi8 gentoo"
+          else
+            distros="${{ github.event.inputs.distro_list }}"
+          fi
+          flag=""
+          for i in $distros
           do
             for j in indimail indimail-mta
             do
@@ -34,11 +47,18 @@ jobs:
                 docker push "ghcr.io/${{ github.repository_owner }}/$j:$i"
                 docker image tag "ghcr.io/${{ github.repository_owner }}/$j:$i" docker.io/cprogrammer/$j:$i
                 docker push docker.io/cprogrammer/$j:$i
+              else
+                cat $i.$j.log
+                flag="$flag $j:$i"
               fi
               /bin/rm -f Dockerfile
               gzip $i.$j.log
             done
           done
+          if [ -n "$flag" ] ; then
+            echo "docker build failed for $flag"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v2
         with:
           name: buildall-bin=from-src
diff --git a/.github/workflows/buildall-src-image.yml b/.github/workflows/buildall-src-image.yml
--- a/.github/workflows/buildall-src-image.yml
+++ b/.github/workflows/buildall-src-image.yml
@@ -7,6 +7,13 @@ name: buildall-src push script
 
 on:
   workflow_dispatch:
+    # Inputs the workflow accepts.
+    inputs:
+      distro_list:
+        # Friendly description to be shown in the UI instead of 'name'
+        Distro List: 'distro list'
+        # Input has to be provided for the workflow to run
+        required: false
 
 jobs:
   build_and_push:
@@ -24,7 +31,13 @@ jobs:
       - name: build
         run: |
           set +e
-          for i in alpine archlinux stream8 stream9 ubi8 gentoo
+          if [ -z "${{ github.event.inputs.distro_list }}"  ] ; then
+            distros="alpine archlinux stream8 stream9 ubi8 gentoo"
+          else
+            distros="${{ github.event.inputs.distro_list }}"
+          fi
+          flag=""
+          for i in $distros
           do
             echo "Using indimail-src/$i.src for build"
             cp indimail-src/$i.src Dockerfile
@@ -33,10 +46,17 @@ jobs:
               docker image tag "docker.io/cprogrammer/indimail-src:$i" "ghcr.io/${{ github.repository_owner }}/indimail-src:$i"
               docker push docker.io/cprogrammer/indimail-src:$i
               docker push ghcr.io/${{ github.repository_owner }}/indimail-src:$i
+            else
+              cat $i.log
+              flag="$flag $i"
             fi
             /bin/rm -f Dockerfile
             gzip $i.log
           done
+          if [ -n "$flag" ] ; then
+            echo "docker build failed for $flag"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v2
         with:
           name: buildall-bin=from-src
diff --git a/.github/workflows/buildall-web-from-obs.yml b/.github/workflows/buildall-web-from-obs.yml
--- a/.github/workflows/buildall-web-from-obs.yml
+++ b/.github/workflows/buildall-web-from-obs.yml
@@ -35,6 +35,7 @@ jobs:
           else
             distros="${{ github.event.inputs.distro_list }}"
           fi
+          flag=""
           for i in $distros
           do
             echo "Using webmail/$i/Dockerfile for build"
@@ -44,10 +45,17 @@ jobs:
               docker push "ghcr.io/${{ github.repository_owner }}/indimail-web:$i"
               docker image tag "ghcr.io/${{ github.repository_owner }}/indimail-web:$i" docker.io/cprogrammer/indimail-web:$i
               docker push docker.io/cprogrammer/indimail-web:$i
+            else
+              cat $i.log
+              flag="$flag $i"
             fi
             /bin/rm -f Dockerfile
             gzip $i.log
           done
+          if [ -n "$flag" ] ; then
+            echo "docker build failed for $flag"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v2
         with:
           name: buildall-bin=from-src
diff --git a/.github/workflows/buildall-web-from-src.yml b/.github/workflows/buildall-web-from-src.yml
--- a/.github/workflows/buildall-web-from-src.yml
+++ b/.github/workflows/buildall-web-from-src.yml
@@ -22,6 +22,7 @@ jobs:
       - name: build
         run: |
           set +e
+          flag=""
           for i in indimail-src/*.indimail-web.bin
           do
             name=$(basename $i |cut -d. -f1)
@@ -32,10 +33,17 @@ jobs:
               docker push "ghcr.io/${{ github.repository_owner }}/indimail-web:$name"
               docker image tag "ghcr.io/${{ github.repository_owner }}/indimail-web:$name" docker.io/cprogrammer/indimail-web:$name
               docker push docker.io/cprogrammer/indimail-web:$name
+            else
+              cat $name.log
+              flag="$flag $name"
             fi
             /bin/rm -f Dockerfile
             gzip $name.log
           done
+          if [ -n "$flag" ] ; then
+            echo "docker build failed for $flag"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v2
         with:
           name: buildall-bin=from-src
